// Reels Recommendation Agent - Dataset Definition

/**
 * 8 Fictional/Anonymized Reels that the student scrolls through.
 * Covers entertainment, gaming, coding, AI, gadgets, career, memes, and tech news.
 * Includes real-world YouTube Shorts/Video embed IDs.
 */
const INPUT_REELS = [
  {
    id: "reel_java_meme",
    title: "Introduction to Computer Science & Coding",
    creator: "cs50",
    duration: 15,
    youtube_id: "y62a5cQ7jL0",
    thumbnail: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=120&auto=format&fit=crop",
    description: "Welcome to CS50! An entry-level introduction to variables, conditions, loops, and software compilation.",
    transcript: "Welcome to CS50! This course is about computational thinking and problem-solving. We will explore how computers represent values, run statements sequentially, compile source code, and run programs in memory.",
    visuals: "Harvard lecture hall, interactive whiteboard, animations showing binary numbers converting to ASCII characters.",
    category_weights: {
      "Career": 0.8,
      "Java": 0.2,
      "Entertainment": 0.3
    },
    tags: ["cs50", "programming", "intro", "computer-science", "basics"]
  },
  {
    id: "reel_swe_lifestyle",
    title: "But what is a Neural Network? (ML Basics)",
    creator: "3blue1brown",
    duration: 45,
    youtube_id: "aircAruvnKk",
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780efad99a?w=120&auto=format&fit=crop",
    description: "A beautiful mathematical visualization explaining artificial neurons, layers, and weights.",
    transcript: "Let's demystify neural networks. We look at connected layers of nodes representing activation weights. Signals pass from inputs to outputs, mathematically extracting patterns.",
    visuals: "Network graphs of connected neurons lighting up layer-by-layer as hand-written digits are recognized.",
    category_weights: {
      "AI": 0.9,
      "Career": 0.1,
      "Entertainment": 0.2
    },
    tags: ["ai", "machine-learning", "neural-networks", "3blue1brown", "math"]
  },
  {
    id: "reel_interview_joke",
    title: "The Dynamic Programming Interview (Joke)",
    creator: "neetcode",
    duration: 30,
    youtube_id: "rL5obz425LI",
    thumbnail: "https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=120&auto=format&fit=crop",
    description: "A breakdown of dynamic programming algorithms and recursive optimizations for coding interviews.",
    transcript: "Why rewrite solutions to overlapping subproblems? Memoization caches values in a hash map, dropping recursion time from exponential O(2^N) to linear O(N)!",
    visuals: "Split screens illustrating recursion trees pruning redundant branches and populating memo tables.",
    category_weights: {
      "DSA": 0.7,
      "Career": 0.5,
      "Entertainment": 0.5
    },
    tags: ["dsa", "interview", "leetcode", "neetcode", "dynamic-programming"]
  },
  {
    id: "reel_laptop_review",
    title: "Demystifying Big O Notation & Scaling",
    creator: "freecodecamp",
    duration: 60,
    youtube_id: "V6mKVRU1evU",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=120&auto=format&fit=crop",
    description: "An educational overview explaining how algorithms scale relative to inputs (O(1), O(N), O(N log N)).",
    transcript: "Big O measures how execution scaling behaves. O(1) is constant time: lookups are instant. O(N) is linear: searching an unsorted array. Avoid O(N^2) nested loops in production!",
    visuals: "Graphs showing time vs input size curves, execution bars, and code comparisons.",
    category_weights: {
      "DSA": 0.9,
      "Career": 0.2,
      "Hardware": 0.1
    },
    tags: ["dsa", "big-o", "complexity", "scaling", "freecodecamp"]
  },
  {
    id: "reel_ai_hype",
    title: "10 AI Tools to Make You Rich in 2 Weeks! (Anti-Hype Trap)",
    creator: "hype_tech",
    duration: 20,
    youtube_id: "tIeHLnjs5U8",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=120&auto=format&fit=crop",
    description: "Don't miss the AI gold rush! Use these hidden prompt hacks to start passive income businesses overnight.",
    transcript: "AI is replacing coders! If you aren't using ChatGPT to write entire websites and sell them on Fiverr, you are losing out. Here are 10 secret prompts that will do all the work while you sleep.",
    visuals: "Flashing dollar signs, robot hands throwing gold coins, dramatic zoom-ins on code generated by AI.",
    category_weights: {
      "Entertainment": 0.9,
      "AI": 0.1
    },
    tags: ["ai", "hype", "passive-income", "chatgpt", "side-hustle"]
  },
  {
    id: "reel_security",
    title: "Hacking the School Grade Portal (Meme)",
    creator: "network_chuck",
    duration: 25,
    youtube_id: "rrM1Q1pS49g",
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=120&auto=format&fit=crop",
    description: "When the principal asks why everyone got an A+ in Computer Science...",
    transcript: "Just open DevTools, select the grade element, change the innerHTML to A+, hit Enter... and boom! I'm in. Wait, why did it reset when I refreshed the page? Oh no, database validation is active!",
    visuals: "Green terminal lines scrolling, matrix style digital rain, dramatic keyboard tapping sound effects.",
    category_weights: {
      "Cybersecurity": 0.8,
      "Entertainment": 0.4
    },
    tags: ["hacking", "cybersecurity", "devtools", "meme", "web-security"]
  },
  {
    id: "reel_cloud",
    title: "Why Our App Crashed: Server Maintenance Day",
    creator: "devops_dan",
    duration: 40,
    youtube_id: "318O8f6tHl0",
    thumbnail: "https://images.unsplash.com/photo-1600132806370-bf17e65e942f?w=120&auto=format&fit=crop",
    description: "Deploying to production on a Friday. What could possibly go wrong?",
    transcript: "So we pushed a quick change to the database migration script. Suddenly, the API servers started throwing 500 errors. The container network crashed because the subnet ran out of IPs. Time to fire up Kubernetes cluster logs.",
    visuals: "AWS console dashboard showing red warnings, slack alert notifications popping up, terminals tailing logs.",
    category_weights: {
      "Cloud": 0.8,
      "Career": 0.3,
      "Entertainment": 0.2
    },
    tags: ["cloud", "kubernetes", "devops", "aws", "sysadmin"]
  },
  {
    id: "reel_gaming",
    title: "Can I Speedrun Coding a Minecraft Clone in 5 Minutes?",
    creator: "javidx9",
    duration: 35,
    youtube_id: "vsLBErLWBhA",
    thumbnail: "https://images.unsplash.com/photo-1612287230202-1bf1d85d1bdf?w=120&auto=format&fit=crop",
    description: "Attempting to build voxel engines using pure C++ and OpenGL. Speedrun challenge!",
    transcript: "Five minutes on the clock. We set up the window context, compile the vertex shader, generate block meshes, and use octree traversal for rapid voxel raycasting. Minecraft blocks are loading!",
    visuals: "Furious typing, side-by-side timer ticking down, wireframe blocks rendering on a window.",
    category_weights: {
      "Gaming": 0.8,
      "DSA": 0.3,
      "Entertainment": 0.4
    },
    tags: ["gaming", "game-dev", "minecraft", "speedrun", "opengl"]
  }
];

const RECOMMENDED_LIBRARY = [
  {
    id: "rec_hld_netflix",
    title: "System Design: How Netflix Handles Millions of Streams",
    creator: "neetcode",
    youtube_id: "psQzyFpUGb0",
    thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=120&auto=format&fit=crop",
    transcript: "Ever wonder what happens when you press Play on Netflix? The system uses a Content Delivery Network (CDN) called Open Connect. Instead of streaming from a central database in the US, Netflix pre-caches video files in local ISP servers physically close to you. This reduces network latency and eliminates buffering. Let's look at the database architecture.",
    category: "HLD",
    difficulty: "Intermediate",
    confidence_score: "High",
    relevance_vector: { "HLD": 0.9, "Career": 0.4 },
    learning_outcome: "Understand CDNs, latency reduction, and geographically distributed caching systems."
  },
  {
    id: "rec_hld_databases",
    title: "System Design 101: SQL vs. NoSQL Databases",
    creator: "cs50",
    youtube_id: "W2Z5DpXpTII",
    thumbnail: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=120&auto=format&fit=crop",
    transcript: "Should you choose SQL or NoSQL? Use relational SQL (like PostgreSQL) when you need ACID compliance and complex queries (e.g., banking systems). Choose NoSQL (like MongoDB) when you need horizontal scalability, high write speeds, and unstructured JSON data formats (e.g., social media feeds). Here is how replication works on both.",
    category: "HLD",
    difficulty: "Beginner",
    confidence_score: "High",
    relevance_vector: { "HLD": 0.8, "Cloud": 0.3 },
    learning_outcome: "Differentiate between relational databases and document stores based on scalability needs."
  },
  {
    id: "rec_hld_loadbalancer",
    title: "How Load Balancers Keep Websites from Crashing",
    creator: "neetcode",
    youtube_id: "i0z_v_QZ0F4",
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=120&auto=format&fit=crop",
    transcript: "When millions of users access a site at once, a Load Balancer acts as the traffic cop. It distributes incoming HTTP requests across a pool of servers using algorithms like Round Robin or Least Connections. It also runs health checks; if a server dies, the load balancer reroutes traffic automatically to prevent outages. This is horizontal scaling in action.",
    category: "HLD",
    difficulty: "Intermediate",
    confidence_score: "High",
    relevance_vector: { "HLD": 0.9, "Cloud": 0.5 },
    learning_outcome: "Explain the purpose of load balancers and horizontal scaling algorithms."
  },
  {
    id: "rec_dsa_big_o",
    title: "Demystifying Big O Notation in 60 Seconds",
    creator: "3blue1brown",
    youtube_id: "g2o22C3CRfU",
    thumbnail: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=120&auto=format&fit=crop",
    transcript: "Big O measures how your code scales as input size grows. O(1) is constant time: looking up a value in a hash table takes the same time whether there are 10 items or 10 million. O(N) is linear: searching an unsorted array requires checking every element. O(N log N) is sorting. Avoid O(N^2) nested loops in production, they will throttle your servers!",
    category: "DSA",
    difficulty: "Beginner",
    confidence_score: "High",
    relevance_vector: { "DSA": 0.9, "Career": 0.3 },
    learning_outcome: "Analyze algorithm time complexity and understand execution scaling."
  },
  {
    id: "rec_dsa_dynamic_prog",
    title: "What is Dynamic Programming? Memoization Explained",
    creator: "neetcode",
    youtube_id: "Hdr64lKQ3e4",
    thumbnail: "https://images.unsplash.com/photo-1516116211223-4c359a36beec?w=120&auto=format&fit=crop",
    transcript: "Dynamic Programming is just smart caching! If you solve the Fibonacci sequence recursively, you compute the same sub-problems over and over. By storing those results in a dictionary (memoization), we reduce the time complexity from exponential O(2^N) down to linear O(N). Don't solve the same problem twice; cache it!",
    category: "DSA",
    difficulty: "Advanced",
    confidence_score: "Medium",
    relevance_vector: { "DSA": 0.9, "Career": 0.6 },
    learning_outcome: "Understand memoization, recursion reduction, and space-time trade-offs."
  },
  {
    id: "rec_dsa_graphs",
    title: "How GPS Find Paths: Dijkstra's Algorithm",
    creator: "neetcode",
    youtube_id: "EFg3u_E6eHU",
    thumbnail: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=120&auto=format&fit=crop",
    transcript: "How does Google Maps find the fastest route? It models the roads as a weighted graph, where intersections are nodes and roads are edges with weights representing traffic/distance. It uses Dijkstra's Algorithm, which visits the nearest unvisited node, updates the shortest path estimates for its neighbors, and repeats until the target is reached.",
    category: "DSA",
    difficulty: "Intermediate",
    confidence_score: "High",
    relevance_vector: { "DSA": 0.9 },
    learning_outcome: "Understand graph traversal and shortest-path calculation in network structures."
  },
  {
    id: "rec_java_garbage",
    title: "Java Memory Management: How Garbage Collection Works",
    creator: "3blue1brown",
    youtube_id: "UnaDY7r4tks",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=120&auto=format&fit=crop",
    transcript: "Java developers don't delete objects manually. Java's Garbage Collector (GC) runs in the JVM background, searching the Heap memory for objects that no longer have active references in the Stack. Once found, it automatically reclaims that memory. Learn the difference between the G1 GC and ZGC to optimize your spring applications.",
    category: "Java",
    difficulty: "Intermediate",
    confidence_score: "High",
    relevance_vector: { "Java": 0.9, "Hardware": 0.2 },
    learning_outcome: "Explain heap allocation and how the JVM automatically reclaims unused references."
  },
  {
    id: "rec_java_multithread",
    title: "Understanding Java Virtual Threads (Project Loom)",
    creator: "3blue1brown",
    youtube_id: "5E0L2ZkF6w0",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=120&auto=format&fit=crop",
    transcript: "Traditional Java threads correspond 1-to-1 to operating system threads. They are heavy and memory-intensive, capping concurrency at a few thousand. In Java 21, Virtual Threads allow millions of concurrent tasks to run on the JVM by mapping multiple virtual threads to a tiny pool of carrier OS threads. It's a game-changer for high-throughput network applications.",
    category: "Java",
    difficulty: "Advanced",
    confidence_score: "Medium",
    relevance_vector: { "Java": 0.9, "HLD": 0.4 },
    learning_outcome: "Contrast OS-bound threads with lightweight user-space scheduling in Java 21."
  },
  {
    id: "rec_ai_neural_net",
    title: "How Neural Networks Actually Learn",
    creator: "3blue1brown",
    youtube_id: "Ilg3gGewQ5U",
    thumbnail: "https://images.unsplash.com/photo-1677442136019-21780efad99a?w=120&auto=format&fit=crop",
    transcript: "Neural networks aren't magic—they are math. They consist of layers of weights and biases. When an image of a handwritten '3' is passed, the network makes a guess. We compute the error (the 'loss') and use backpropagation with calculus to adjust the weights in the opposite direction of the gradient. This gradient descent is how computers learn patterns.",
    category: "AI",
    difficulty: "Intermediate",
    confidence_score: "High",
    relevance_vector: { "AI": 0.9 },
    learning_outcome: "Understand the mathematical principles of gradient descent, backpropagation, and loss functions."
  },
  {
    id: "rec_ai_embeddings",
    title: "What are Vector Embeddings and Cosine Similarity?",
    creator: "3blue1brown",
    youtube_id: "ySEx_BqxpGY",
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=120&auto=format&fit=crop",
    transcript: "How do LLMs understand semantic meaning? They convert words or sentences into vectors—long arrays of numbers representing coordinates in a high-dimensional space. Words with similar meanings (like 'cat' and 'kitten') are placed close together. We measure this closeness using Cosine Similarity, which computes the angle between the two vectors.",
    category: "AI",
    difficulty: "Intermediate",
    confidence_score: "High",
    relevance_vector: { "AI": 0.9, "DSA": 0.3 },
    learning_outcome: "Explain vector representations of textual concepts and similarity measurements."
  },
  {
    id: "rec_cloud_docker",
    title: "Docker vs. Virtual Machines: The Real Difference",
    creator: "cs50",
    youtube_id: "fqMOX6jjhGo",
    thumbnail: "https://images.unsplash.com/photo-1605745341112-85968b19335b?w=120&auto=format&fit=crop",
    transcript: "Why did Docker take over the world? A Virtual Machine packages a full guest operating system, which takes minutes to boot and gigabytes of RAM. Docker containers share the host operating system's kernel, isolating only the application code and libraries. This makes containers lightweight (megabytes) and bootable in milliseconds. Great for microservices!",
    category: "Cloud",
    difficulty: "Beginner",
    confidence_score: "High",
    relevance_vector: { "Cloud": 0.9, "Hardware": 0.2 },
    learning_outcome: "Distinguish operating-system level virtualization from full hardware virtualization."
  },
  {
    id: "rec_cloud_kubernetes",
    title: "Kubernetes: Container Orchestration Explained Simply",
    creator: "neetcode",
    youtube_id: "PzhX733sP30",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=120&auto=format&fit=crop",
    transcript: "If you have hundreds of Docker containers running, how do you manage them? Kubernetes is the orchestrator. If a container crashes, Kubernetes launches a replacement. If traffic spikes, Kubernetes scales your pods horizontally. It handles networking, load balancing, and rolling updates without downtime. This is cloud-native reliability.",
    category: "Cloud",
    difficulty: "Advanced",
    confidence_score: "High",
    relevance_vector: { "Cloud": 0.9, "HLD": 0.4 },
    learning_outcome: "Explain the self-healing and auto-scaling properties of container orchestration platforms."
  },
  {
    id: "rec_cyber_sql_injection",
    title: "How SQL Injection Attacks Work (and How to Prevent)",
    creator: "neetcode",
    youtube_id: "23FqyeT-_wE",
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=120&auto=format&fit=crop",
    transcript: "SQL Injection occurs when untrusted user input is directly concatenated into a database query. A hacker typing `' OR 1=1 --` into a login box can bypass authentication and dump the entire user table. To fix this, always use Prepared Statements and Parameterized Queries, which treat input strictly as data, never executable code.",
    category: "Cybersecurity",
    difficulty: "Beginner",
    confidence_score: "High",
    relevance_vector: { "Cybersecurity": 0.9, "Career": 0.2 },
    learning_outcome: "Understand injection vulnerabilities and code-level defenses using parameterized statements."
  },
  {
    id: "rec_cyber_asymmetric",
    title: "How Public Key Cryptography Keeps the Web Secure",
    creator: "3blue1brown",
    youtube_id: "GSIDS_lvRv4",
    thumbnail: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=120&auto=format&fit=crop",
    transcript: "When you visit an HTTPS site, how is your connection private? It uses Asymmetric Cryptography. You have two keys: a Public Key (given to everyone to encrypt messages) and a Private Key (kept secret to decrypt). If Bob encrypts a message with Alice's public key, only Alice's private key can read it. This is the foundation of SSL/TLS handshakes.",
    category: "Cybersecurity",
    difficulty: "Intermediate",
    confidence_score: "High",
    relevance_vector: { "Cybersecurity": 0.9 },
    learning_outcome: "Differentiate between public and private keys in encrypting web sessions."
  },
  {
    id: "rec_hardware_cpu_cache",
    title: "How CPU Cache Speeds Up Code: L1, L2, L3 Caches",
    creator: "3blue1brown",
    youtube_id: "XW9pD97hC20",
    thumbnail: "https://images.unsplash.com/photo-1601524909162-be87252be298?w=120&auto=format&fit=crop",
    transcript: "CPUs are incredibly fast, but reading data from RAM takes hundreds of clock cycles (the memory wall). To solve this, CPUs use cache memory (L1, L2, L3) built directly into the processor chip. L1 cache is super fast (nanoseconds) but tiny. Writing cache-friendly code (like traversing arrays sequentially instead of jumping memory addresses) keeps your CPU active and fast.",
    category: "Hardware",
    difficulty: "Advanced",
    confidence_score: "Medium",
    relevance_vector: { "Hardware": 0.9, "DSA": 0.4 },
    learning_outcome: "Understand cache locality, CPU caching layers, and optimizing memory access patterns."
  },
  {
    id: "rec_career_clean_code",
    title: "3 Clean Code Principles to Write Production-Ready Software",
    creator: "cs50",
    youtube_id: "CNEPeD22j-Q",
    thumbnail: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=120&auto=format&fit=crop",
    transcript: "Writing working code is easy; writing maintainable code is hard. Remember these three rules: 1) KISS: Keep It Simple, Stupid—avoid over-engineering. 2) DRY: Don't Repeat Yourself—extract repetitive logic into functions. 3) Single Responsibility: A function or class should do exactly one thing. Senior engineers write readable code, junior engineers write complex code.",
    category: "Career",
    difficulty: "Beginner",
    confidence_score: "High",
    relevance_vector: { "Career": 0.9 },
    learning_outcome: "Apply design patterns and principles (DRY, SOLID, KISS) to improve software longevity."
  }
];

const PRESETS = {
  "built_in_trap": {
    name: "Built-in Trap (Shallow vs. Deep Interest)",
    description: "Watches programming jokes, a lifestyle vlog, a laptop review, and a Java meme. A shallow algorithm recommends basic Java loops. Our agent should infer Software Engineering & Career interest, recommending HLD or DSA concepts.",
    history: [
      {
        reel_id: "reel_java_meme",
        watch_time: 15,
        liked: true,
        saved: false,
        shared: false,
        loops: 2,
        comment: "This is literally me every single morning."
      },
      {
        reel_id: "reel_swe_lifestyle",
        watch_time: 40,
        liked: false,
        saved: true,
        shared: false,
        loops: 1,
        comment: ""
      },
      {
        reel_id: "reel_interview_joke",
        watch_time: 30,
        liked: true,
        saved: true,
        shared: true,
        loops: 1,
        comment: "Dreading my Leetcode interview tomorrow, omg."
      },
      {
        reel_id: "reel_laptop_review",
        watch_time: 60,
        liked: false,
        saved: false,
        shared: true,
        loops: 1,
        comment: "Thermal scaling and complexity limits look crazy."
      }
    ]
  },
  "ai_engineer": {
    name: "AI & ML Explorer",
    description: "The student spends their session watching neural network vids and ML basics. They skip Java loops immediately. The agent should recommend AI vector embeddings or dynamic programming.",
    history: [
      {
        reel_id: "reel_swe_lifestyle",
        watch_time: 45,
        liked: true,
        saved: true,
        shared: true,
        loops: 2,
        comment: "Neural network backprop calculus is incredible."
      },
      {
        reel_id: "reel_java_meme",
        watch_time: 2,
        liked: false,
        saved: false,
        shared: false,
        loops: 1,
        comment: "Too basic."
      }
    ]
  },
  "hardware_cloud": {
    name: "Sysadmin & Infrastructure Enthusiast",
    description: "Watches the system complexity and scaling benchmarks. The system should infer high interest in Cloud Infrastructure, System Design, and Hardware, recommending Kubernetes or CPU Cache optimization.",
    history: [
      {
        reel_id: "reel_laptop_review",
        watch_time: 60,
        liked: true,
        saved: true,
        shared: false,
        loops: 2,
        comment: "Performance complexity scaling is key."
      },
      {
        reel_id: "reel_java_meme",
        watch_time: 5,
        liked: false,
        saved: false,
        shared: false,
        loops: 1,
        comment: ""
      }
    ]
  }
};

// Export to window object for browser access
if (typeof window !== "undefined") {
  window.INPUT_REELS = INPUT_REELS;
  window.RECOMMENDED_LIBRARY = RECOMMENDED_LIBRARY;
  window.PRESETS = PRESETS;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { INPUT_REELS, RECOMMENDED_LIBRARY, PRESETS };
}
